name: fdstools_stuttermark
description:  Mark potential stutter products
keywords:
  - fastq
  - artefacts
  - STR
tools:
  - bwa:
      description: |
        Mark potential stutter products by assuming a fixed maximum percentage of stutter product vs the parent sequence.
        If not present, Stuttermark adds a new column named 'flags' to the output. The flags column will contain 'STUTTER' 
        for possible stutter products. A sequence is considered a possible stutter product if its total read count is less 
        than or equal to the maximum number of expected stutter reads. The maximum number of stutter reads is computed by 
        assuming a fixed percentage of stutter product compared to the originating sequence. Stuttermark requires TSSV-style 
        sequences (automatically converting sequences to this format if necessary) and detects possible stutter products by
        comparing sequences that have the same repeat blocks but different numbers of repeats for one or more of their blocks.
      homepage: https://github.com/Jerrythafast/FDSTools
      documentation: https://www.fdstools.nl/tools.html#stuttermark
      licence: ["GPL-3.0-or-later"]
      identifier: ""
input:
  - reads:
    - meta:
        type: map
        description: |
          Groovy Map containing reference information.
          e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: Input  fastq files
  - library_file:
    - meta:
      type: map
      description: |
          Groovy Map containing reference information.
          e.g. [ id:'test', single_end:false ]
    - library_file:  |
        library file with marker definitions
output:
  - tssv_out:
      - meta:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
      - tssv_out:
          type: file
          description: TSSV output files
          pattern: "*.{fastq,fq}.gz"
  - paired_fq:
      - meta2:
          type: map
          description: |
            Groovy Map containing reference information.
            e.g. [ id:'test', single_end:false ]
      - fastq:
          type: file
          description: Paired and marker matched fastq files
          pattern: "*.{fastq,fq}.gz"          
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@sfilges"
maintainers:
  - "@sfilges"